Pasta added, readme fixed up, symlink and .env standard implemented

diff --git a/pastit b/pastit
--- a/pastit
+++ b/pastit
@@ -1,23 +1,35 @@
 #!/bin/bash
+# pastit
 
-#### CONFIG - CHANGE THESE ####
+# Swap to repo directory.
+cd "$(dirname "$(readlink -f "$0")")" || exit 1
 
-# Set this to your zipline url*
-URL=ENTER_YOUR_ZIPLINE_URL_HERE/api/upload
+# Check .env exists
+filename=".env"
+if [ ! -f "$filename" ]; then
+     echo -e ".env file not found!\nTo configure pasta and run this command:\n\ncp .env.example .env\n\nThen edit .env with a text editor to include your hosting domain and Auth Token from zipline!"
+     exit 1
+fi
 
-## *If your host machine is the same machine you are running this script on, I suggest using http://localhost:{PORT NUMBER} (obviously replace {PORT NUMBER} with the port number you setup zipline on) instead, since it is easier.
+# Load .env
+source .env
 
-# Set this to your zipline authorization token (I found this in the generated sharex config file)
-authorizationtoken=ENTER_YOUR_ZIPLINE_AUTHORIZATION_TOKEN_HERE
-
+#### CONFIG OPTIONS ####
 # Default extension (.sh/.py/.zsh)
 # This will be used if the file you provided has no common extension, I.E. stuff like .zshrc, or /etc/hosts. This helps zipline offer a default type of syntax highlighting, usually base this around what OS youre using. So by default I made it 'sh' so that extensionless files get bash script syntax highlighting.
 defaultextension=sh
 
 # Consider files starting with dot as extensionless (true/false)
 considerFilesStartingWithDotExtensionless=true
-
 #### END CONFIG ####
+
+if [[ "${url}" != */ ]]; then
+  url="${url}/"
+fi
+
+URL="${url}api/upload"
+authorizationtoken="${authtoken}"
+
 #### SCRIPT START ####
 # Check if text is provided via stdin
 if [ -p /dev/stdin ]; then
